/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/greek_statue_head.glb --transform 
Files: public/models/greek_statue_head.glb [21.1MB] > C:\Users\acer\Desktop\ASA\portfolio\PortFolioWeb\portfolio\greek_statue_head-transformed.glb [659.23KB] (97%)
Author: Annika Schwartz (https://sketchfab.com/wishberry)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/greek-statue-head-6310ffd720aa4a478c1d476dd7141c6b
Title: Greek Statue Head
*/

import * as React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GLTFResult = {
  nodes: {
    ["lambert1-material"]: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.Material;
  };
};

type ModelProps = React.ComponentProps<"group">;

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/models/greek_statue_head-transformed.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["lambert1-material"].geometry}
        material={materials.lambert1}
        position={[-0.073, -1.113, -0.038]}
        scale={0.038}
      />
    </group>
  );
}

useGLTF.preload("/models/greek_statue_head-transformed.glb");
